//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAMAI.Win.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TAMAI.Win.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV files|*.csv|All files|*.*.
        /// </summary>
        internal static string FilterExportSpectra {
            get {
                return ResourceManager.GetString("FilterExportSpectra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAS data files|*.ustas;*.fstas|usTAS data files|*.ustas|fsTAS data files|*.fstas|All files|*.*.
        /// </summary>
        internal static string FilterOpenSavedTas {
            get {
                return ResourceManager.GetString("FilterOpenSavedTas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fsTAS data files|*.fstas|All files|*.*.
        /// </summary>
        internal static string FilterSaveFsTas {
            get {
                return ResourceManager.GetString("FilterSaveFsTas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usTAS data files|*.ustas|All files|*.*.
        /// </summary>
        internal static string FilterSaveUsTas {
            get {
                return ResourceManager.GetString("FilterSaveUsTas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Analysis.
        /// </summary>
        internal static string MenuAnalysis {
            get {
                return ResourceManager.GetString("MenuAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Time evolution.
        /// </summary>
        internal static string MenuAnalysisTimeEvolution {
            get {
                return ResourceManager.GetString("MenuAnalysisTimeEvolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        internal static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string MenuFileOpen {
            get {
                return ResourceManager.GetString("MenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;TAS data.
        /// </summary>
        internal static string MenuFileOpenSavedTas {
            get {
                return ResourceManager.GetString("MenuFileOpenSavedTas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;usTAS.
        /// </summary>
        internal static string MenuFileOpenUsTas {
            get {
                return ResourceManager.GetString("MenuFileOpenUsTas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string MenuFileSave {
            get {
                return ResourceManager.GetString("MenuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save as.
        /// </summary>
        internal static string MenuFileSaveAs {
            get {
                return ResourceManager.GetString("MenuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tool.
        /// </summary>
        internal static string MenuTool {
            get {
                return ResourceManager.GetString("MenuTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export &amp;Spectra.
        /// </summary>
        internal static string MenuToolExportSpectra {
            get {
                return ResourceManager.GetString("MenuToolExportSpectra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate TAS file with TAMAI for Win.
        /// </summary>
        internal static string MenuToolRegExts {
            get {
                return ResourceManager.GetString("MenuToolRegExts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while drawing spectra..
        /// </summary>
        internal static string MessageErrorDrawingSpectra {
            get {
                return ResourceManager.GetString("MessageErrorDrawingSpectra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the spectra..
        /// </summary>
        internal static string MessageErrorExportSpectra {
            get {
                return ResourceManager.GetString("MessageErrorExportSpectra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the TAS data..
        /// </summary>
        internal static string MessageErrorOpen {
            get {
                return ResourceManager.GetString("MessageErrorOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the TAS data..
        /// </summary>
        internal static string MessageErrorSave {
            get {
                return ResourceManager.GetString("MessageErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TAS data have been successfully saved..
        /// </summary>
        internal static string MessageFileSaved {
            get {
                return ResourceManager.GetString("MessageFileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file format..
        /// </summary>
        internal static string MessageNotSupportedFormat {
            get {
                return ResourceManager.GetString("MessageNotSupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the current data before exit the application?.
        /// </summary>
        internal static string MessageSaveBeforeClose {
            get {
                return ResourceManager.GetString("MessageSaveBeforeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the current data before open new one?.
        /// </summary>
        internal static string MessageSaveBeforeOpen {
            get {
                return ResourceManager.GetString("MessageSaveBeforeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The spectra have been successfully saved..
        /// </summary>
        internal static string MessageSpectraSaved {
            get {
                return ResourceManager.GetString("MessageSpectraSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string PlaceholderSampleComment {
            get {
                return ResourceManager.GetString("PlaceholderSampleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample name.
        /// </summary>
        internal static string PlaceholderSampleName {
            get {
                return ResourceManager.GetString("PlaceholderSampleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAMAI for Win.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string TableHeaderFittingArgs {
            get {
                return ResourceManager.GetString("TableHeaderFittingArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string TableHeaderFrom {
            get {
                return ResourceManager.GetString("TableHeaderFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string TableHeaderFunc {
            get {
                return ResourceManager.GetString("TableHeaderFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string TableHeaderShow {
            get {
                return ResourceManager.GetString("TableHeaderShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time constant.
        /// </summary>
        internal static string TableHeaderTimeConstant {
            get {
                return ResourceManager.GetString("TableHeaderTimeConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string TableHeaderTo {
            get {
                return ResourceManager.GetString("TableHeaderTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abs(Y).
        /// </summary>
        internal static string TextAbsSignal {
            get {
                return ResourceManager.GetString("TextAbsSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log(X).
        /// </summary>
        internal static string TextSemilogX {
            get {
                return ResourceManager.GetString("TextSemilogX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log(Y).
        /// </summary>
        internal static string TextSemilogY {
            get {
                return ResourceManager.GetString("TextSemilogY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export spectra.
        /// </summary>
        internal static string TitleExportSpectra {
            get {
                return ResourceManager.GetString("TitleExportSpectra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open TAS data.
        /// </summary>
        internal static string TitleOpenSavedTas {
            get {
                return ResourceManager.GetString("TitleOpenSavedTas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open usTAS data directory.
        /// </summary>
        internal static string TitleOpenUsTas {
            get {
                return ResourceManager.GetString("TitleOpenUsTas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save fsTAS data.
        /// </summary>
        internal static string TitleSaveFsTas {
            get {
                return ResourceManager.GetString("TitleSaveFsTas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save usTAS data.
        /// </summary>
        internal static string TitleSaveUsTas {
            get {
                return ResourceManager.GetString("TitleSaveUsTas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time evolution.
        /// </summary>
        internal static string TitleTimeEvolution {
            get {
                return ResourceManager.GetString("TitleTimeEvolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder.
        /// </summary>
        internal static string ToastOpenDir {
            get {
                return ResourceManager.GetString("ToastOpenDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string ToastOpenFile {
            get {
                return ResourceManager.GetString("ToastOpenFile", resourceCulture);
            }
        }
    }
}
